# Generated by Django 4.0.2 on 2022-03-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagement', '0002_userrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='delivered_status',
            field=models.CharField(choices=[('cancel', 'cancel'), ('delivered', 'delivered'), ('requested', 'requested')], default='requested', max_length=50),
        ),
    ]
