# Generated by Django 4.0.2 on 2022-03-11 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagement', '0003_alter_userrequest_delivered_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
